version: '2.1'
services: 
  server:
    build: ./server
    expose:
     - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: node app.js
  client:
    build: ./client
    expose:
     - ${REACT_APP_PORT}
    environment: 
      REACT_APP_PORT: ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    links:
       - server  
    command: serve -s build  -l ${REACT_APP_PORT} 