version: '2.1'

services:
  server:
    image: server
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 9696:9696
      - 9229:9229
    command: node --inspect=0.0.0.0:9229 app.js